<?xml version="1.0"?>
<package format="2">
  <name>mppi_controller</name>
  <version>1.0.0</version>
  <description>The mppi_controller package</description>
  <maintainer email="942568052@qq.com">Zhanyu Guo</maintainer>
  <license>GPL3</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>angles</depend>
  <depend>costmap_2d</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_core</depend>
  <depend>nav_msgs</depend>
  <depend>pluginlib</depend>
  <depend>roscpp</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>controller</depend>
  <depend>system_config</depend>

  <export>
    <nav_core plugin="${prefix}/mppi_controller_plugin.xml" />

  </export>
</package>