syntax = "proto3";

package rmp.pb.controller;

message MPPIController {
  float min_turning_r = 1;
  bool regenerate_noises = 2;

  // constraint critic
  bool constraint_critic_enabled = 3;
  uint32 constraint_critic_cost_power = 4;
  float constraint_critic_cost_weight = 5;
  float constraint_critic_vx_max = 6;
  float constraint_critic_vy_max = 7;
  float constraint_critic_vx_min = 8;

  // cost critic
  bool cost_critic_enabled = 9;
  uint32 cost_critic_cost_power = 10;
  float cost_critic_cost_weight = 11;
  float cost_critic_critical_cost = 12;
  uint32 cost_critic_near_collision_cost = 13;
  float cost_critic_collision_cost = 14;
  float cost_critic_near_goal_distance = 15;
  uint32 trajectory_point_step = 16;
}